  
version: '3.5'

services:
  app:
    build:
      context: ./
      target: runner
    ports:
      - '3002:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_WORDPRESS_KEY: ${NEXT_PUBLIC_WORDPRESS_KEY}
volumes:
  nextpro: