
version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: ${MODE_NODE_ENV}
      NEXT_PUBLIC_WORDPRESS_KEY: ${NEXT_PUBLIC_WORDPRESS_KEY}