  
version: '3.5'

services:
  app:
    build:
      context: ./
      target: builder
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3002:3000'
    volumes:
      - .:/app
    environment:
      NEXT_PUBLIC_WORDPRESS_KEY: ${NEXT_PUBLIC_WORDPRESS_KEY}
