import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./providers";
import { ThemeSwitcher } from "./ThemeSwitcher";
import AuthContext from "./Providers/NextAuth";
import IaChat from "./IaChat";
import { cn } from "./_utils/tailwindMerge";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wealth Expo LA | App Web Oficial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <AuthContext>
            {/* <ThemeSwitcher /> */}
            <NavBar />
            {children}
          </AuthContext>
          <IaChat />
        </ThemeProvider>
      </body>
    </html>
  );
}
