import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./providers";
import { ThemeSwitcher } from "./ThemeSwitcher";
import AuthContext from "./Providers/NextAuth";
import IaChat from "./IaChat";
import { cn } from "./_utils/tailwindMerge";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <AuthContext>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
            {/* <ThemeSwitcher /> */}
            <NavBar />
            {children}
          </ThemeProvider>
        </AuthContext>
        <IaChat />
      </body>
    </html>
  );
}
